### ISSUE TITLE
MimeMessageViewer handling weblinks

### ISSUE THREAD

**Issue by large** [Enough-Software/enough_mail_flutter#11]
Thank you for a great library! 
Tested it and works very well.
There is an mailtoDelegate for the mailto:, but how do you handle weblinks hrefs http: and https:?
In my app I do previews of mails and I want to block all navigation. Is this a feature or possible?

**Comment by robert-virkus** [comment]
This makes sense. You can now specify the `urlLauncherDelegate`:
`Future<bool> Function(String url)? urlLauncherDelegate`
Return `true` when the URL was handled, 

This handler just swallows any URLs:

```dart
MimeMessageViewer(
  urlLauncherDelegate: (url) => Future.value(true),
),
```
I haven't released this yet, but you can depend on the git version to test this:
```yaml
dependencies:
  enough_mail_flutter: 
    git:
      url: https://github.com/Enough-Software/enough_mail_flutter.git
```

If this works for you please close this issue.
